networks:
  internal:
    driver: bridge

volumes:
  mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_ROOT}/mysql

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_ROOT}/wordpress

services:
  mariadb:
    container_name: mariadb
    build: srcs/requirements/mariadb
    restart: always
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - internal
    env_file: mariadb.env

  wordpress:
    container_name: wordpress
    build: srcs/requirements/wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    expose:
      - 9000
    networks:
      - internal
    env_file:
      - mariadb.env
      - wordpress.env

  nginx:
    container_name: nginx
    build: srcs/requirements/nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - internal
    tty: true
