networks:
  docker-network:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: srcs/requirements/mariadb
    restart: always
    expose:
      - 3306
    volumes:
      - ~/data/mysql:/var/lib/mysql
    networks:
      - docker-network
    env_file: mariadb.env

  wordpress:
    container_name: wordpress
    build: srcs/requirements/wordpress
    restart: always
    volumes:
      - ~/data/wp:/var/www/html
    expose:
      - 9000
    networks:
      - docker-network
    env_file:
      - mariadb.env
      - wordpress.env

  nginx:
    container_name: nginx
    build: srcs/requirements/nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - ~/data/wp:/var/www/html
    networks:
      - docker-network
    tty: true
