volumes:
  db:
  wp:


networks:
  internal:

    # 기본값은 bridge
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#driver-1

services:
  mariadb:
    build: srcs/requirements/mariadb
    restart: always
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal
    env_file: "mariadb.env"

  wordpress:
    build: srcs/requirements/wordpress
    restart: always
    volumes:
      - wp:/var/www/html
    expose:
      - 9000
    networks:
      - internal
    env_file:
      - "mariadb.env"
      - "wordpress.env"

  # nginx:
  #   image: alpine:3.16.0
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - data:/var/www/html
  #   networks:
  #     - internal
  #   tty: true
