site_name: 냉혹한 Inception의 세계

theme:
  name: material

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
